// This file was automatically generated by Kmisc::registerFunctions()

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP count_newlines(SEXP x_, SEXP n_);
SEXP get_roxygen_index(SEXP split_, SEXP row_);
SEXP readfile(SEXP path_);
SEXP find_next_char(SEXP chr_, SEXP txt_, SEXP ind_);
SEXP find_prev_char(SEXP chr_, SEXP txt_, SEXP ind_);
SEXP find_matching_char__fwd(SEXP chr_, SEXP cmp_, SEXP txt_, SEXP ind_);
SEXP find_matching_char__bwd(SEXP chr_, SEXP cmp_, SEXP txt_, SEXP ind_);
SEXP parse_args(SEXP x_);

R_CallMethodDef callMethods[]  = {
  {"C_count_newlines", (DL_FUNC) &count_newlines, 2},
  {"C_get_roxygen_index", (DL_FUNC) &get_roxygen_index, 2},
  {"C_readfile", (DL_FUNC) &readfile, 1},
  {"C_find_next_char", (DL_FUNC) &find_next_char, 3},
  {"C_find_prev_char", (DL_FUNC) &find_prev_char, 3},
  {"C_find_matching_char__fwd", (DL_FUNC) &find_matching_char__fwd, 4},
  {"C_find_matching_char__bwd", (DL_FUNC) &find_matching_char__bwd, 4},
  {"C_parse_args", (DL_FUNC) &parse_args, 1},
  {NULL, NULL, 0}
};

void R_init_attributes(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

