// This file was automatically generated by Kmisc::registerFunctions()

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP readfile(SEXP path_);
SEXP find_next_char(SEXP chr_, SEXP txt_, SEXP ind_);
SEXP find_prev_char(SEXP chr_, SEXP txt_, SEXP ind_);
SEXP find_matching_char__fwd(SEXP chr_, SEXP cmp_, SEXP txt_, SEXP ind_);
SEXP find_matching_char__bwd(SEXP chr_, SEXP cmp_, SEXP txt_, SEXP ind_);

R_CallMethodDef callMethods[]  = {
  {"C_readfile", (DL_FUNC) &readfile, 1},
  {"C_find_next_char", (DL_FUNC) &find_next_char, 3},
  {"C_find_prev_char", (DL_FUNC) &find_prev_char, 3},
  {"C_find_matching_char__fwd", (DL_FUNC) &find_matching_char__fwd, 4},
  {"C_find_matching_char__bwd", (DL_FUNC) &find_matching_char__bwd, 4},
  {NULL, NULL, 0}
};

void R_init_attributes(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

