compileDefaultAttributes <- function(pkgDir, verbose, RcppExports.R) {

  DESCRIPTION <- as.list(read.dcf( file.path(pkgDir, "DESCRIPTION") )[1, ])
  pkgname <- DESCRIPTION$Package

  LinkingTo <- gsub("^[[:space:]]*", "",
    unlist( strsplit( gsub("\\r|\\n", " ", DESCRIPTION$LinkingTo), ",[[:space:]]+" ) )
  )

  srcDir <- file.path(pkgDir, "src")

  ## Get rid of the old RcppExports files if they exist
  if (file.exists(file <- file.path(pkgDir, "src", "RcppExports.cpp"))) {
    unlink(file)
  }

  if (file.exists(file <- file.path(pkgDir, "R", "RcppExports.R"))) {
    unlink(file)
  }

  ## Get the C++ source files
  files <- list.files(srcDir, full.names=TRUE, pattern=".cc$|.cpp$")

  ## Parse the attributes
  export_attrs <- lapply(files, parse_attrs, keep="Rcpp::export")

  ## Get the definitions for each export
  exports <- unlist( lapply(export_attrs, parse_exports), recursive=FALSE )

  if (length(exports)) {
    defns <- lapply(exports, generate_export, pkgDir=pkgDir)

    ## Write out the RcppExports.cpp file

    ## If we're linking to RcppArmadillo, include that instead of Rcpp
    if ("RcppArmadillo" %in% LinkingTo) {
      RcppIncludes <- "#include <RcppArmadillo.h>"
    } else {
      RcppIncludes <- "#include <Rcpp.h>"
    }

    RcppHeader <- paste(sep = "\n",
      "// This file was generated by attributes::compileAttributes",
      "// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393",
      ""
    )

    RcppExports.cpp <- paste( sep="\n",
      RcppHeader,
      RcppIncludes,
      "using namespace Rcpp;",
      "",
      do.call( function(...)
        paste(..., sep="\n", collapse="\n"),
        lapply(defns, function(x) paste(x, collapse="\n"))
      )
    )

    cat(RcppExports.cpp, file=file.path(pkgDir, "src", "RcppExports.cpp"))

    make_R_function <- function(export) {

      ## Special-case Dots, NamedDots
      which_dots <- which(export$arg_types %in% c("Dots", "NamedDots", "Rcpp::Dots", "Rcpp::NamedDots"))
      export$arg_names[which_dots] <- "..."

      peq <- function(x, y) paste(x, y, sep = " = ")
      fn_name <- paste(pkgname, export$func, sep = "_")
      pkg_arg <- peq("PACKAGE", shQuote(pkgname))
      export_args <- export$arg_names
      export_args[export_args == "..."] <- "environment()"
      if (length(export$arg_names)) {
        fn_args <- paste(pkg_arg, paste(export_args, collapse = ", "), sep = ", ")
      } else {
        fn_args <- pkg_arg
      }
      callArgs <- c(
        shQuote(fn_name),
        fn_args
      )
      .Call <- paste0(".Call(", paste(callArgs, collapse = ", "), ")")
      if (export$type == "void") .Call <- paste0("invisible(", .Call, ")")

      Rfun <- paste( sep="\n",
        tab(0, export$roxygen),
        tab(0, paste0(export$R_name, " <- function(", paste(export$arg_names, collapse=", "), ") {")),
        tab(1, .Call),
        tab(0, "}")
      )
    }

    if (RcppExports.R) {
      RcppExports.R <- paste(unlist(lapply(exports, make_R_function)), collapse = "\n")

      RcppHeader <- paste(sep = "\n",
                          "# This file was generated by attributes::compileAttributes",
                          "# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393"
      )

      cat(
        paste(sep="\n", RcppHeader, RcppExports.R),
        file=file.path(pkgDir, "R", "RcppExports.R")
      )
    }

  }

}
